### PR TITLE
Upload simple handler was improved according to MDS-638 and MDS-670

### PR DESCRIPTION
**Pull request by iderikon**
Key is checked for existence before be written according to MDS-638.
Couple retries mechanism was implemented for simple upload according to MDS-670.

Both features should be considered together because of reasons described in MDS-638.

Reviewers: @shindo .

### CODE REVIEW

**Comment by iderikon** [comment]
> It's better to use check_for_update default value here, not just true, isn't it?

The same problem is with others options. I think they can be refactored all together in another one PR.

**Comment by iderikon** [comment]
> What about from_current_exception() as a name for this method?
Yeap, it would be better.

**Comment by shindo** [comment]
Looks good.

**Comment by shindo** [comment]
Looks good.

**Pull request merged**
